export { default as Navbar } from './NavBar';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Home } from './Home';
export { default as Activities } from './Activities';
export { default as CreateAnActivity } from './CreateAnActivity';
export { default as EditAnActivity } from './EditAnActivity';
export { default as ActivityRoutines } from './ActivityRoutines';
export { default as MyRoutines } from './MyRoutines';
export { default as Routines } from './Routines';
export { default as EditRoutine } from './EditRoutine'
export { default as EditRoutineActivity } from './EditRoutineActivity'
export { default as UserRoutines } from './UserRoutines'